networks:
  app-tier:
    driver: bridge

volumes:
  kafka-data:
    name: kafka-data
    external: false

services:
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    volumes:
      - kafka-data:/bitnami/kafka
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: 'controller,broker'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '0@kafka:9093'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - '8080:8080'
    networks:
      - app-tier
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9092'
    depends_on:
      - kafka
  kafdrop:
    image: 'obsidiandynamics/kafdrop:latest'
    ports:
      - '9000:9000'
    networks:
      - app-tier
    environment:
      KAFKA_BROKERCONNECT: 'kafka:9092'
    depends_on:
      - kafka
  